<a href="https://colab.research.google.com/github/luckyluk89/data-science-bootcamp/blob/master/0.1%20Wprowadzenie_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tablice

In [0]:
print("Hello Colab")

In [0]:
import numpy as np
print(dir(np))

In [0]:
help(np.array)

In [0]:
x = np.array([1,3])

In [0]:
x

In [0]:
print(x)

In [0]:
type(x)

In [0]:
x.ndim

In [0]:
x.shape

In [0]:
x.size

In [0]:
x.dtype

dtype('int64')

In [0]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [0]:
x.ndim

2

In [0]:
x.shape

(2, 2)

3D Array

In [0]:
x = np.array(
    [[[1,2,3],
      [1,2,3],
      [1,2,3]],
     
     [[1,2,3],
      [1,2,3],
      [1,2,3]]]
)
x

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [0]:
x.ndim

3

In [0]:
x.shape

(2, 3, 3)

### Typy danych

# Tworzenie tablic

In [0]:
np.zeros(4,10)

TypeError: ignored

In [0]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
 np.full(shape=(2,2), fill_value=2, dtype=float)

array([[2., 2.],
       [2., 2.]])

In [0]:
help(np.reshape)

# Podstawowe operacje na liczbach

In [0]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [0]:
A+B

array([6, 0, 7, 4])

In [0]:
A-B

In [0]:
A*B

In [0]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


# Generowanie liczb pseudolosowych

In [0]:
np.random.randint(low=44, high=120, size=(10,2))

array([[ 55,  80],
       [ 84,  84],
       [ 79,  55],
       [ 64,  56],
       [ 62,  54],
       [ 46,  54],
       [ 62,  65],
       [116,  62],
       [ 46, 117],
       [ 72,  88]])

# Podstawowe funkcje tablicowe

In [0]:
np.exp(1)

2.718281828459045

In [0]:
bool(-1)

True

In [0]:
A= np.random.rand(5)
A

array([0.75502193, 0.41299696, 0.75247301, 0.00484583, 0.21901459])

In [0]:
A(np.argmax(A))

TypeError: ignored

In [0]:
A[np.argmax(A)]

0.7550219283925327

# Indeksowanie i wycinanie tablic


In [0]:
import numpy as np

In [18]:
A = np.arange(20)
A = A.reshape(4,5)
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [22]:
A[:3,:4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

# Iteraja po tablicach, zmiana rozmiaru i maski logiczne

In [24]:
A[1,2]=14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
A = np.arange(start=-10,stop=10,step=0.5)
A


array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [42]:
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])